package com.LexiLucha.LexiLucha

import com.LexiLucha.LexiLucha.dal.QuestionRepository
import com.LexiLucha.LexiLucha.model.Question
import com.LexiLucha.LexiLucha.model.User
import com.LexiLucha.LexiLucha.model.enums.LANGUAGE
import com.LexiLucha.LexiLucha.model.enums.QUESTIONMODE
import com.LexiLucha.LexiLucha.service.UserService
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.annotation.Value
import org.springframework.boot.ApplicationArguments
import org.springframework.boot.ApplicationRunner
import org.springframework.context.annotation.Bean
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.stereotype.Service

@Service
class Dataloader @Autowired constructor(val questionRepo: QuestionRepository, val userService: UserService): ApplicationRunner  {

    @Value("\${spring.jpa.hibernate.ddl-auto}")
    lateinit var DDL_SETTING: String

    override fun run(args: ApplicationArguments?) {
        val questions: ArrayList<Question> = ArrayList()

        // Spanish Questions
        questions.add(Question("¿Dónde está la biblioteca?", "Where is the library?", "I need to study.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cómo te llamas?", "What's your name?", "Nice to meet you.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuántos años tienes?", "How old are you?", "I like your haircut.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué hora es?", "What time is it?", "Let's go to the park.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Dónde vives?", "Where do you live?", "I love your dog.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te gusta hacer?", "What do you like to do?", "It's a beautiful day.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu comida favorita?", "What's your favorite food?", "I prefer reading books.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué quieres hacer mañana?", "What do you want to do tomorrow?", "Let's go to the beach.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cómo estás?", "How are you?", "I'm feeling tired.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Dónde trabajas?", "Where do you work?", "I need a vacation.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué estás haciendo?", "What are you doing?", "I'm watching TV.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu deporte favorito?", "What's your favorite sport?", "I like hiking.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu canción favorita?", "What's your favorite song?", "Music makes me happy.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué estudias en la universidad?", "What do you study at the university?", "I want to travel.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes mascotas?", "Do you have pets?", "I enjoy cooking.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu libro favorito?", "What's your favorite book?", "Reading is fun.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué quieres ser en el futuro?", "What do you want to be in the future?", "I'm a good cook.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu lugar favorito para vacacionar?", "What's your favorite vacation spot?", "I like to dance.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu película favorita de terror?", "What's your favorite horror movie?", "I enjoy gardening.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Dónde te gustaría vivir?", "Where would you like to live?", "I'm learning to paint.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué tipo de música te gusta?", "What kind of music do you like?", "I like to travel.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué idiomas hablas?", "What languages do you speak?", "I want to learn French.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu pasatiempo favorito?", "What's your favorite hobby?", "I love the beach.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna alergia?", "Do you have any allergies?", "I enjoy hiking.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te gustaría cenar esta noche?", "What would you like for dinner tonight?", "I like swimming.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu programa de televisión favorito?", "What's your favorite TV show?", "I like to cook.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué deportes practicas?", "What sports do you play?", "I'm a good swimmer.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu destino de viaje soñado?", "What's your dream travel destination?", "I enjoy painting.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes hermanos mayores?", "Do you have older siblings?", "I like to go hiking.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te hace feliz?", "What makes you happy?", "I'm a movie buff.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu restaurante favorito?", "What's your favorite restaurant?", "I like photography.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu película de ciencia ficción favorita?", "What's your favorite science fiction movie?", "I enjoy camping.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu destino de viaje favorito?", "What's your favorite travel destination?", "I like to write.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te motiva?", "What motivates you?", "I'm a nature lover.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu postre favorito?", "What's your favorite dessert?", "I enjoy knitting.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te hace reír?", "What makes you laugh?", "I like to play chess.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu plato principal favorito?", "What's your favorite main dish?", "I enjoy bird watching.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te preocupa?", "What worries you?", "I like to go fishing.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu color favorito?", "What's your favorite color?", "I enjoy playing soccer.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu animal favorito?", "What's your favorite animal?", "I love to read books.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué quieres hacer el fin de semana?", "What do you want to do on the weekend?", "Let's go for a walk.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu lugar de vacaciones ideal?", "What's your ideal vacation spot?", "I like to watch movies.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu hobby principal?", "What's your main hobby?", "I enjoy playing the guitar.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna meta a largo plazo?", "Do you have any long-term goals?", "I want to learn to cook.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu película favorita de comedia?", "What's your favorite comedy movie?", "I like to paint.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes hermanos menores?", "Do you have younger siblings?", "I like to travel.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te inspira?", "What inspires you?", "I enjoy going for a run.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu serie de televisión preferida?", "What's your favorite TV series?", "I love gardening.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu plato étnico favorito?", "What's your favorite ethnic dish?", "I like photography.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna fobia?", "Do you have any phobias?", "I enjoy playing chess.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu bebida favorita?", "What's your favorite drink?", "I like to go fishing.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu deporte de equipo favorito?", "What's your favorite team sport?", "I'm a history buff.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu día de la semana preferido?", "What's your favorite day of the week?", "I like to cook.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu asignatura favorita?", "What's your favorite subject?", "I enjoy swimming.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te gustaría aprender en el futuro?", "What would you like to learn in the future?", "I'm a nature enthusiast.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu tienda favorita?", "What's your favorite store?", "I like to knit.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu estación del año preferida?", "What's your favorite season?", "I'm a tech geek.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes un artista o banda favorita?", "Do you have a favorite artist or band?", "I enjoy bird watching.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te gustaría mejorar en ti mismo?", "What would you like to improve about yourself?", "I like to go camping.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu superhéroe favorito?", "Who's your favorite superhero?", "I enjoy writing poetry.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu lugar para relajarte?", "What's your go-to relaxation spot?", "I like to play video games.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna rutina de ejercicios?", "Do you have an exercise routine?", "I'm a history enthusiast.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu comida rápida preferida?", "What's your favorite fast food?", "I like to go hiking.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu libro de no ficción favorito?", "What's your favorite non-fiction book?", "I enjoy playing soccer.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes una película clásica favorita?", "Do you have a favorite classic movie?", "I love to read books.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu lugar histórico favorito?", "What's your favorite historical site?", "Let's go for a walk.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna tradición familiar especial?", "Do you have any special family traditions?", "I like to watch movies.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu talento oculto?", "What's your hidden talent?", "I enjoy playing the guitar.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Qué te hace sentir agradecido?", "What makes you feel grateful?", "I want to learn to cook.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu comida picante favorita?", "What's your favorite spicy food?", "I like to paint.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna meta de viaje?", "Do you have a travel goal?", "I like to travel.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu película favorita de acción?", "What's your favorite action movie?", "I enjoy going for a run.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu plato de desayuno preferido?", "What's your favorite breakfast dish?", "I love gardening.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes una mascota?", "Do you have a pet?", "I like photography.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Cuál es tu lugar natural favorito?", "What's your favorite natural place?", "I enjoy playing chess.", language = LANGUAGE.SPANISH))
        questions.add(Question("¿Tienes alguna meta profesional?", "Do you have any career goals?", "I like to go fishing.", language = LANGUAGE.SPANISH))

        // Greek Questions
        questions.add(Question("Πού είναι η βιβλιοθήκη;", "Where is the library?", "I need to study.", language = LANGUAGE.GREEK))
        questions.add(Question("Πώς σε λένε;", "What's your name?", "Nice to meet you.", language = LANGUAGE.GREEK))
        questions.add(Question("Πόσων ετών είσαι;", "How old are you?", "I like your haircut.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι ώρα είναι;", "What time is it?", "Let's go to the park.", language = LANGUAGE.GREEK))
        questions.add(Question("Πού μένεις;", "Where do you live?", "I love your dog.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι σου αρέσει να κάνεις;", "What do you like to do?", "It's a beautiful day.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποια είναι η αγαπημένη σου τροφή;", "What's your favorite food?", "I prefer reading books.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι θες να κάνεις αύριο;", "What do you want to do tomorrow?", "Let's go to the beach.", language = LANGUAGE.GREEK))
        questions.add(Question("Πώς είσαι;", "How are you?", "I'm feeling tired.", language = LANGUAGE.GREEK))
        questions.add(Question("Πού δουλεύεις;", "Where do you work?", "I need a vacation.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι κάνεις;", "What are you doing?", "I'm watching TV.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου σπορ;", "What's your favorite sport?", "I like hiking.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου τραγούδι;", "What's your favorite song?", "Music makes me happy.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι σπουδάζεις στο πανεπιστήμιο;", "What do you study at the university?", "I want to travel.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κατοικίδια;", "Do you have pets?", "I enjoy cooking.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου βιβλίο;", "What's your favorite book?", "Reading is fun.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι θες να κάνεις σήμερα το βράδυ;", "What would you like for dinner tonight?", "I like swimming.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου εστιατόριο;", "What's your favorite restaurant?", "I like to cook.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου φαγητό γρήγορης ετοιμασίας;", "What's your favorite fast food?", "I like to go hiking.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι είδους μουσική σου αρέσει;", "What kind of music do you like?", "I like to travel.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιες γλώσσες μιλάς;", "What languages do you speak?", "I want to learn French.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου χόμπι;", "What's your favorite hobby?", "I love the beach.", language = LANGUAGE.GREEK))
        questions.add(Question("Πού θα ήθελες να ζήσεις;", "Where would you like to live?", "I'm learning to paint.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι είναι αυτό που σε εμπνέει;", "What inspires you?", "I enjoy going for a run.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου χρώμα;", "What's your favorite color?", "I enjoy playing soccer.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου ζώο;", "What's your favorite animal?", "I love to read books.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι θα ήθελες να κάνεις το Σαββατοκύριακο;", "What do you want to do on the weekend?", "Let's go for a walk.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το ιδανικό σημείο διακοπών σου;", "What's your ideal vacation spot?", "I like to watch movies.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το κυρίως σου χόμπι;", "What's your main hobby?", "I enjoy playing the guitar.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποιο μακροπρόθεσμο στόχο;", "Do you have any long-term goals?", "I want to learn to cook.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποια είναι η αγαπημένη σου ταινία κωμωδίας;", "What's your favorite comedy movie?", "I like to paint.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις καλλιτέχνη ή συγκρότημα που αγαπάς;", "Do you have a favorite artist or band?", "I enjoy bird watching.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι θα ήθελες να βελτιώσεις στον εαυτό σου;", "What would you like to improve about yourself?", "I like to go camping.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιος είναι ο αγαπημένος σου υπερήρωας;", "Who's your favorite superhero?", "I enjoy writing poetry.", language = LANGUAGE.GREEK))
        questions.add(Question("Πού είναι το αγαπημένο σου μέρος για χαλάρωση;", "What's your go-to relaxation spot?", "I like to play video games.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποια ρουτίνα ασκήσεων;", "Do you have an exercise routine?", "I'm a history enthusiast.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου φαγητό παγωτού;", "What's your favorite ice cream flavor?", "I like to go fishing.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου βιβλίο μη φαντασίας;", "What's your favorite non-fiction book?", "I enjoy playing soccer.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποια αγαπημένη κλασική ταινία;", "Do you have a favorite classic movie?", "I love to read books.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου ιστορικό μέρος;", "What's your favorite historical site?", "Let's go for a walk.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποια ιδιαίτερη οικογενειακή παράδοση;", "Do you have any special family traditions?", "I like to watch movies.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το κρυφό σου ταλέντο;", "What's your hidden talent?", "I enjoy playing the guitar.", language = LANGUAGE.GREEK))
        questions.add(Question("Τι σε κάνει να νιώθεις ευγνώμος;", "What makes you feel grateful?", "I want to learn to cook.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου καυτερό φαγητό;", "What's your favorite spicy food?", "I like to paint.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποιο ταξιδιωτικό στόχο;", "Do you have a travel goal?", "I like to travel.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποια είναι η αγαπημένη σου ταινία δράσης;", "What's your favorite action movie?", "I enjoy going for a run.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου πρωινό πιάτο;", "What's your favorite breakfast dish?", "I love gardening.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποιο κατοικίδιο;", "Do you have a pet?", "I like photography.", language = LANGUAGE.GREEK))
        questions.add(Question("Ποιο είναι το αγαπημένο σου φυσικό μέρος;", "What's your favorite natural place?", "I enjoy playing chess.", language = LANGUAGE.GREEK))
        questions.add(Question("Έχεις κάποιον επαγγελματικό στόχο;", "Do you have any career goals?", "I like to go fishing.", language = LANGUAGE.GREEK))

        // Japanese Questions
        questions.add(Question("Onamae wa nan desu ka?", "What is your name?", "My favorite color is blue.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Doko kara kimashita ka?", "Where are you from?", "I enjoy playing video games.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Nani o shiteimasu ka?", "What do you do?", "I love watching movies in my free time.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Shumi wa nan desu ka?", "What is your hobby?", "I often listen to music.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Suki na tabemono wa nan desu ka?", "What is your favorite food?", "I like to travel and explore new places.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Kyou wa dou deshita ka?", "How was your day today?", "I'm interested in learning new languages.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Kazoku wa imasu ka?", "Do you have a family?", "I enjoy reading books in my spare time.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Nanigo o hanasemasu ka?", "What languages can you speak?", "I practice martial arts as a form of exercise.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Shuumatsu wa nani o shimasu ka?", "What do you do on weekends?", "I have a pet cat named Mochi.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Shourai no yume wa arimasu ka?", "Do you have any future dreams?", "I like to cook Japanese cuisine.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Saigo ni mita eiga wa nan desu ka?", "What was the last movie you watched?", "I enjoy gardening in my backyard.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Suki na kisetsu wa nan desu ka?", "What is your favorite season?", "I often go hiking in the mountains.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Gakusei desu ka, soretomo hataraiteimasu ka?", "Are you a student or do you work?", "I have a collection of vintage stamps.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Ryokou ga suki desu ka?", "Do you like to travel?", "I like to watch anime in my free time.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Ima nanji desu ka?", "What time is it now?", "I enjoy painting as a creative outlet.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Suki na ongaku janru wa nan desu ka?", "What is your favorite music genre?", "I like to go fishing.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Arigatou gozaimasu", "Thank you very much", "I like to take long walks in the evening.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Ohayou gozaimasu", "Good morning", "I have a collection of antique books.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Konbanwa", "Good evening", "I enjoy solving puzzles in my free time.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Gomen nasai", "I'm sorry", "I practice meditation to relax.", language=LANGUAGE.JAPANESE))
        questions.add(Question("O genki desu ka?", "How are you?", "I like to cook traditional Japanese dishes.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Hajimemashite", "Nice to meet you", "I have a pet dog named Sakura.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Sumimasen", "Excuse me", "I enjoy listening to classical music.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Yoroshiku onegaishimasu", "Please", "I like to draw landscapes.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Oishii desu", "It's delicious", "I practice yoga for physical and mental well-being.", language=LANGUAGE.JAPANESE))
        questions.add(Question("Genki desu", "I'm well", "I have a talent for playing the piano.", language=LANGUAGE.JAPANESE))

        // German Questions
        questions.add(Question("Wie heißt du?", "What is your name?", "I enjoy reading books.", language=LANGUAGE.GERMAN))
        questions.add(Question("Woher kommst du?", "Where are you from?", "I play soccer in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was machst du?", "What do you do?", "I enjoy listening to music in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was ist dein Hobby?", "What is your hobby?", "I love cooking and trying new recipes.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was ist dein Lieblingsessen?", "What is your favorite food?", "I love traveling and exploring new places.", language=LANGUAGE.GERMAN))
        questions.add(Question("Wie war dein Tag heute?", "How was your day today?", "I am interested in art history.", language=LANGUAGE.GERMAN))
        questions.add(Question("Hast du Geschwister?", "Do you have siblings?", "I paint and have a small art gallery at home.", language=LANGUAGE.GERMAN))
        questions.add(Question("Welche Sprachen sprichst du?", "What languages can you speak?", "I love writing poetry.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was machst du am Wochenende?", "What do you do on weekends?", "I have a dog named Max.", language=LANGUAGE.GERMAN))
        questions.add(Question("Hast du Zukunftspläne?", "Do you have any future plans?", "I play chess in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was war der letzte Film, den du gesehen hast?", "What was the last movie you watched?", "I enjoy being in nature and taking long walks.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was ist deine Lieblingsjahreszeit?", "What is your favorite season?", "I love cooking and trying new recipes from around the world.", language=LANGUAGE.GERMAN))
        questions.add(Question("Bist du Student oder arbeitest du?", "Are you a student or do you work?", "I collect antique furniture.", language=LANGUAGE.GERMAN))
        questions.add(Question("Magst du es zu reisen?", "Do you like to travel?", "I enjoy watching documentaries.", language=LANGUAGE.GERMAN))
        questions.add(Question("Wie spät ist es jetzt?", "What time is it now?", "I play the piano as a hobby.", language=LANGUAGE.GERMAN))
        questions.add(Question("Was ist dein Lieblingsmusikgenre?", "What is your favorite music genre?", "I enjoy fishing in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Danke schön", "Thank you very much", "I play video games in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Guten Morgen", "Good morning", "I am interested in astronomy.", language=LANGUAGE.GERMAN))
        questions.add(Question("Guten Abend", "Good evening", "I paint landscapes.", language=LANGUAGE.GERMAN))
        questions.add(Question("Entschuldigung", "Excuse me", "I practice yoga for physical and mental well-being.", language=LANGUAGE.GERMAN))
        questions.add(Question("Wie geht es dir?", "How are you?", "I enjoy reading historical novels.", language=LANGUAGE.GERMAN))
        questions.add(Question("Freut mich", "Nice to meet you", "I have a collection of old coins.", language=LANGUAGE.GERMAN))
        questions.add(Question("Bitte", "Please", "I am interested in modern art.", language=LANGUAGE.GERMAN))
        questions.add(Question("Es schmeckt gut", "It's delicious", "I hike in the mountains.", language=LANGUAGE.GERMAN))
        questions.add(Question("Mir geht es gut", "I'm well", "I play table tennis in my free time.", language=LANGUAGE.GERMAN))
        questions.add(Question("Ich liebe dich", "I love you", "I am involved in volunteer work.", language=LANGUAGE.GERMAN))
        questions.add(Question("Ich vermisse dich", "I miss you", "I collect postcards from different countries.", language=LANGUAGE.GERMAN))
        questions.add(Question("Gute Nacht", "Good night", "I am interested in photography.", language=LANGUAGE.GERMAN))
        questions.add(Question("Alles Gute zum Geburtstag", "Happy birthday", "I love cooking and trying new recipes from around the world.", language=LANGUAGE.GERMAN))
        questions.add(Question("Prost", "Cheers", "I play board games with friends.", language=LANGUAGE.GERMAN))
        questions.add(Question("Wo ist die nächste U-Bahn-Station?", "Where is the nearest subway station?", "I enjoy dancing salsa.", language=LANGUAGE.GERMAN))

        // Viet Questions
        questions.add(Question("Bạn có sở thích gì không?", "Do you have any hobbies?", "I enjoy playing guitar.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Cuốn sách bạn đọc gần đây là gì?", "What is the last book you read?", "I like reading novels.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Món ăn yêu thích của bạn là gì?", "What is your favorite food?", "I love pho.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Cuối tuần bạn thường làm gì?", "What do you do on weekends?", "I often go to the movies.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bộ phim cuối cùng bạn xem là gì?", "What is the last movie you watched?", "I enjoy watching action movies.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn có ước mơ nghề nghiệp không?", "Do you have any career goals?", "I want to be a successful entrepreneur.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Hãy kể về công việc của bạn.", "Tell me about your job.", "I work in marketing.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Điểm đến du lịch yêu thích của bạn là đâu?", "What is your favorite travel destination?", "I love visiting Hanoi.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích loại nhạc nào?", "What kind of music do you like?", "I enjoy listening to pop music.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn có thói quen làm gì với bạn bè không?", "Do you do things with friends?", "I often go to cafes with friends.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích thể thao nào nhất?", "What is your favorite sport?", "I enjoy playing badminton.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Khi là sinh viên, bạn học ngành gì?", "What did you study when you were a student?", "I studied economics.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích điều gì nhất về Việt Nam?", "What do you like about Vietnam?", "I love the rich history and culture.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Kỳ nghỉ nào là kỳ nghỉ vui nhất của bạn?", "What is probably your most enjoyable holiday?", "I enjoy Tet holiday.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn ăn sushi lần đầu tiên ở đâu?", "Where did you first eat sushi?", "I tried sushi in a Japanese restaurant.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn có thích tập thể dục không?", "Do you like to exercise?", "I go to the gym regularly.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn đang học tiếng Anh không?", "Are you studying SPANISH?", "Yes, I am learning SPANISH.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Không, bạn không thích xem phim à?", "No, don't you like watching movies?", "I prefer reading books.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Cho tôi biết, tên bạn là gì?", "Tell me, what is your name?", "My name is Linh.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn có thể làm gì không?", "What can you do?", "I can speak three languages.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích làm gì nhất khi có khách?", "What do you enjoy doing with guests?", "I like showing them traditional Vietnamese dishes.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Tiếng thở nhỏ của bạn ở nhà dành cho điều gì?", "What is your small sigh at home for?", "It's for relaxation after work.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Kỷ niệm ngoại ô nào là đáng nhớ nhất của bạn?", "What is your fondest memory outdoors?", "Camping by the beach with friends.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Làm thế nào bạn tăng nhận thức trong công việc?", "How do you raise awareness at work?", "I actively participate in team discussions.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Khi nghỉ, bạn thường làm gì?", "What do you do during your vacation?", "I enjoy traveling to new places.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Hôm qua, bạn đã làm gì?", "What did you do yesterday?", "I visited a museum with my family.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn đã sinh ra ở đâu?", "Where on earth were you born?", "I was born in Ho Chi Minh City.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Món ăn bạn ghét nhất là gì?", "What is your least favorite dish?", "I don't like durian.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Khi có thời gian, bạn thích làm gì?", "If you have time, what do you like to do?", "I enjoy playing the piano.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn muốn đi đến đâu ở Nhật Bản?", "Where in Japan would you like to go?", "I want to visit Tokyo.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Nơi bạn đã đến trong kỳ nghỉ hè là đâu?", "Where did you go for summer vacation?", "I visited Da Nang.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bây giờ, bạn đang làm gì không?", "Are you doing something right now?", "I'm working on a project.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Thời tiết ngày mai sẽ thế nào?", "How is the weather tomorrow?", "The forecast says it will be rainy.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Khi đi du lịch, bạn thường mang theo gì?", "What do you take with you when you travel?", "I always bring my camera and journal.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Tài năng đặc biệt của bạn là gì?", "What is your special talent?", "I can play the violin.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Khi rảnh rỗi, bạn thường luyện tập gì?", "When you have time, what do you practice?", "I practice calligraphy.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích chó hay mèo hơn?", "Do you prefer dogs or cats?", "I like dogs more, but I have a cat.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Kết quả của mùa bóng năm nay thế nào?", "How was the football season this year?", "My favorite team did well.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Chiếc xe ô tô của bạn là gì?", "What kind of car do you have?", "I drive a compact car.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Gần đây, bạn đã làm điều gì mới không?", "Have you done anything new recently?", "I started learning how to cook.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Trong nhà, bạn có sở thích gì?", "Do you have any hobbies at home?", "I like painting and gardening.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Cuối tuần, bạn thường làm gì?", "What do you do on weekends?", "I usually spend time with family.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bản nhạc bạn thích là gì?", "What is your favorite song?", "I like listening to Vietnamese folk songs.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Hệ thống tàu điện ở Nhật Bản có thú vị không?", "Is the train system in Japan interesting?", "Yes, it's very efficient and punctual.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn đói chưa?", "Are you hungry?", "Yes, I could go for some pho.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Ban đêm, bạn làm gì?", "What do you do at night?", "I like watching movies before bed.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Kế hoạch của bạn cho ngày mai là gì?", "What are your plans for tomorrow?", "I have a meeting in the morning and then shopping in the afternoon.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Gần đây, có nơi nào bạn muốn ghé thăm không?", "Is there a place you've been wanting to visit lately?", "I'd like to explore more local markets.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bây giờ, bạn có ước mơ nào không?", "Do you have any dreams right now?", "I dream of starting my own business.", language=LANGUAGE.VIETNAMESE))
        questions.add(Question("Bạn thích lái xe ô tô không?", "Do you like driving a car?", "Yes, I find it convenient.", language=LANGUAGE.VIETNAMESE))

        // Mandarin Questions
        questions.add(Question("你有什么爱好吗？", "Do you have any hobbies?", "Mountain biking", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最近读过的书是什么？", "What is the last book you read?", "Starship adventure", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最喜欢的食物是什么？", "What is your favorite food?", "Sparkling kaleidoscope", language=LANGUAGE.MANDARIN))
        questions.add(Question("周末你通常做什么？", "What do you do on weekends?", "Juggling dreams", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最后看的电影是什么？", "What is the last movie you watched?", "Whispering galaxies", language=LANGUAGE.MANDARIN))
        questions.add(Question("你有职业目标吗？", "Do you have any career goals?", "Floating ambitions", language=LANGUAGE.MANDARIN))
        questions.add(Question("告诉我关于你的工作。", "Tell me about your job.", "Paperclip symphony", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最喜欢的旅行目的地是哪里？", "What is your favorite travel destination?", "Ephemeral moonlight", language=LANGUAGE.MANDARIN))
        questions.add(Question("你喜欢什么类型的音乐？", "What kind of music do you like?", "Velvet sunrise", language=LANGUAGE.MANDARIN))
        questions.add(Question("你和朋友有什么共同爱好吗？", "Do you do things with friends?", "Crimson kaleidoscope", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最喜欢的运动是什么？", "What is your favorite sport?", "Whispering zephyr", language=LANGUAGE.MANDARIN))
        questions.add(Question("当你还是学生的时候，你学什么专业的？", "What did you study when you were a student?", "Lunar exploration", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最喜欢越南的什么地方？", "What do you like about Vietnam?", "Sapphire dreams", language=LANGUAGE.MANDARIN))
        questions.add(Question("你可能最喜欢的假期是哪一个？", "What is probably your most enjoyable holiday?", "Aurora reflections", language=LANGUAGE.MANDARIN))
        questions.add(Question("你第一次吃寿司是在哪里？", "Where did you first eat sushi?", "Whispering bamboo", language=LANGUAGE.MANDARIN))
        questions.add(Question("你喜欢锻炼吗？", "Do you like to exercise?", "Cosmic acrobatics", language=LANGUAGE.MANDARIN))
        questions.add(Question("你现在是否在学习英语？", "Are you studying SPANISH?", "Lunar symphony", language=LANGUAGE.MANDARIN))
        questions.add(Question("不喜欢看电影吗？", "No, don't you like watching movies?", "Ethereal illusions", language=LANGUAGE.MANDARIN))
        questions.add(Question("告诉我，你叫什么名字？", "Tell me, what is your name?", "Galactic whispers", language=LANGUAGE.MANDARIN))
        questions.add(Question("你能做什么？", "What can you do?", "Whirling stardust", language=LANGUAGE.MANDARIN))
        questions.add(Question("你在朋友面前喜欢做什么？", "What do you enjoy doing with guests?", "Celestial kaleidoscope", language=LANGUAGE.MANDARIN))
        questions.add(Question("在家里，你小小的叹息是为了什么？", "What is your small sigh at home for?", "Mystical daydreams", language=LANGUAGE.MANDARIN))
        questions.add(Question("在户外最令你难忘的回忆是什么？", "What is your fondest memory outdoors?", "Lunar escapade", language=LANGUAGE.MANDARIN))
        questions.add(Question("在工作中，你如何提高团队意识？", "How do you raise awareness at work?", "Whispering nebula", language=LANGUAGE.MANDARIN))
        questions.add(Question("你休假的时候通常做什么？", "What do you do during your vacation?", "Cosmic odyssey", language=LANGUAGE.MANDARIN))
        questions.add(Question("昨天你做了什么？", "What did you do yesterday?", "Ephemeral memories", language=LANGUAGE.MANDARIN))
        questions.add(Question("你在哪里出生的？", "Where on earth were you born?", "Stellar origins", language=LANGUAGE.MANDARIN))
        questions.add(Question("你最不喜欢的菜是什么？", "What is your least favorite dish?", "Galactic aversions", language=LANGUAGE.MANDARIN))
        questions.add(Question("有时间的话，你喜欢做什么？", "If you have time, what do you like to do?", "Celestial pursuits", language=LANGUAGE.MANDARIN))
        questions.add(Question("你想去日本的哪个地方？", "Where in Japan would you like to go?", "Sakura dreams", language=LANGUAGE.MANDARIN))
        questions.add(Question("今年夏天你去了哪里？", "Where did you go this summer?", "Lunar escapade", language=LANGUAGE.MANDARIN))

        // Lithuanian Questions
        questions.add(Question("Kokių pomėgių turite?", "Do you have any hobbies?", "Adventure seeker, nature photographer", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokia paskutinė knyga, kurią skaitėte?", "What is the last book you read?", "Mystery novel enthusiast, bookworm", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Koks yra jūsų mėgstamiausias maistas?", "What is your favorite food?", "Sushi lover, culinary explorer", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ką paprastai veikiate savaitgaliais?", "What do you do on weekends?", "Theatergoer, outdoor adventurer", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Koks yra paskutinis filmas, kurį žiūrėjote?", "What is the last movie you watched?", "Comedy fan, movie buff", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar turite karjeros tikslų?", "Do you have any career goals?", "Aspiring programmer, business visionary", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Pasakykite man apie savo darbą.", "Tell me about your job.", "IT professional, problem solver", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Koks yra jūsų mėgstamiausias kelionės tikslas?", "What is your favorite travel destination?", "Mountain enthusiast, culture explorer", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokios muzikos žanro mėgstate?", "What kind of music do you like?", "Classical music admirer, pop music enthusiast", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar kartu su draugais kažką veikiate?", "Do you do things with friends?", "Frequent café visitor, social butterfly", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kaip praleidžiate laisvalaikį?", "How do you spend your free time?", "Guitar player, beachcomber", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokį sportą mėgstate?", "What sport do you like?", "Yoga practitioner, soccer enthusiast", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar mėgstate gaminti?", "Do you like cooking?", "Amateur chef, recipe experimenter", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kur gimėte?", "Where were you born?", "City dweller, hometown enthusiast", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kas jums patinka darant su šeima?", "What do you enjoy doing with your family?", "Board game enthusiast, family storyteller", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kaip praėjo jūsų vakaras?", "How was your evening?", "Stargazer, midnight reader", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ką žiūrite televiziją?", "What do you watch on TV?", "Documentary lover, binge-watcher", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar turite augintinį?", "Do you have a pet?", "Pet lover, dog walker", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokia jūsų mėgstamiausia metų laikas?", "What is your favorite season?", "Autumn enthusiast, winter lover", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokie jūsų šeimos tradicijos?", "What are your family traditions?", "Holiday celebrator, family chef", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ką mėgstate valgyti pusryčiams?", "What do you like to eat for breakfast?", "Coffee connoisseur, pancake lover", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar mėgstate keliauti?", "Do you like to travel?", "Wanderlust, travel photographer", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kaip praleidžiate savo gimtadienį?", "How do you celebrate your birthday?", "Birthday cake enthusiast, party planner", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokie yra jūsų ilgalaikiai tikslai?", "What are your long-term goals?", "Dream chaser, goal setter", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar mėgstate žiūrėti saulėlydžius?", "Do you like watching sunsets?", "Sunset admirer, beach lover", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kas jums suteikia energijos?", "What gives you energy?", "Morning jogger, coffee enthusiast", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kaip mėgstate leisti savo atostogas?", "How do you like to spend your vacations?", "Travel explorer, relaxation seeker", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Ar turite pomėgį kalbėti su žmonėmis?", "Do you enjoy talking to people?", "Social butterfly, conversation starter", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kas jums suteikia gyvenimo prasmę?", "What gives meaning to your life?", "Passion pursuer, dream chaser", language=LANGUAGE.LITHUANIAN))
        questions.add(Question("Kokie yra jūsų mėgstamiausi šeimos vakarėlių žaidimai?", "What are your favorite family game night games?", "Game night enthusiast, strategy game lover", language=LANGUAGE.LITHUANIAN))

        // SWEDISH

        questions.add(Question("Vad är dina hobbies?", "What are your hobbies?", "Hiking enthusiast, bookworm", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är den senaste boken du läste?", "What is the last book you read?", "Mystery novel fan, avid reader", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är din favoritmat?", "What is your favorite food?", "Sushi lover, pizza enthusiast", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad brukar du göra på helgerna?", "What do you usually do on weekends?", "Movie buff, nature explorer", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är den senaste filmen du såg?", "What is the last movie you watched?", "Action movie fan, film critic", language=LANGUAGE.SWEDISH))
        questions.add(Question("Har du några karriärmål?", "Do you have any career goals?", "Entrepreneurial spirit, career dreamer", language=LANGUAGE.SWEDISH))
        questions.add(Question("Berätta om ditt jobb.", "Tell me about your job.", "IT professional, problem solver", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är din favoritresedestination?", "What is your favorite travel destination?", "Beach lover, adventure seeker", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vilken typ av musik gillar du?", "What kind of music do you like?", "Jazz enthusiast, classical music lover", language=LANGUAGE.SWEDISH))
        questions.add(Question("Gör du saker med vänner?", "Do you do things with friends?", "Coffee enthusiast, social butterfly", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är din favoritsport?", "What is your favorite sport?", "Soccer fan, tennis player", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad studerade du när du var student?", "What did you study when you were a student?", "Economics major, history buff", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad gillar du med Sverige?", "What do you like about Sweden?", "Nature lover, cultural explorer", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är din mest minnesvärda semester?", "What is your most memorable holiday?", "Road trip adventurer, beachcomber", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad är din första upplevelse med sushi?", "What is your first experience with sushi?", "Sushi tasting experience, culinary adventure", language=LANGUAGE.SWEDISH))
        questions.add(Question("Gillar du att träna?", "Do you like to exercise?", "Yoga practitioner, gym enthusiast", language=LANGUAGE.SWEDISH))
        questions.add(Question("Läser du engelska nu?", "Are you reading SPANISH now?", "Language learner, book lover", language=LANGUAGE.SWEDISH))
        questions.add(Question("Gillar du inte att titta på filmer?", "Don't you like watching movies?", "Movie critic, film buff", language=LANGUAGE.SWEDISH))
        questions.add(Question("Berätta, vad heter du?", "Tell me, what is your name?", "Coffee aficionado, language learner", language=LANGUAGE.SWEDISH))
        questions.add(Question("Vad kan du göra?", "What can you do?", "Multilingual communicator, problem solver", language=LANGUAGE.SWEDISH))

        // REVERSE SPANISH QUESTIONS
        questions.add(Question("What are your hobbies?", "¿Cuáles son tus hobbies?", "Amante de la música, excursionista", language=LANGUAGE.SPANISH, mode= QUESTIONMODE.REVERSE))
        questions.add(Question("What is the last book you read?", "¿Cuál es el último libro que leíste?", "Fanático de la historia, ávido lector", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is your favorite food?", "¿Cuál es tu comida favorita?", "Amante de la cocina, explorador culinario", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What do you usually do on weekends?", "¿Qué haces normalmente los fines de semana?", "Explorador urbano, amante de la naturaleza", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is the last movie you watched?", "¿Cuál es la última película que viste?", "Crítico de cine, aficionado a las comedias", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Do you have any career goals?", "¿Tienes algún objetivo profesional?", "Emprendedor, soñador de carrera", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Tell me about your job.", "Cuéntame sobre tu trabajo.", "Profesional del marketing, solucionador de problemas", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is your favorite travel destination?", "¿Cuál es tu destino de viaje favorito?", "Aventurero, amante de la playa", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What kind of music do you like?", "¿Qué tipo de música te gusta?", "Melómano, aficionado al jazz", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Do you do things with friends?", "¿Haces cosas con amigos?", "Amante del café, explorador social", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is your favorite sport?", "¿Cuál es tu deporte favorito?", "Fanático del fútbol, jugador de tenis", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What did you study when you were a student?", "¿Qué estudiaste cuando eras estudiante?", "Estudiante de economía, amante de la historia", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What do you like about Spain?", "¿Qué te gusta de España?", "Amante de la cultura, explorador de la comida", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is your most memorable holiday?", "¿Cuál es tu día festivo más memorable?", "Aventurero en carretera, amante de la playa", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What is your first experience with paella?", "¿Cuál es tu primera experiencia con la paella?", "Degustador de paella, aventurero culinario", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Do you like to exercise?", "¿Te gusta hacer ejercicio?", "Practicante de yoga, entusiasta del gimnasio", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Are you reading Spanish now?", "¿Estás leyendo español ahora?", "Aprendiz de idiomas, amante de los libros", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Don't you like watching movies?", "¿No te gusta ver películas?", "Crítico de cine, aficionado a las películas", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("Tell me, what is your name?", "Dime, ¿cuál es tu nombre?", "Aficionado al café, aprendiz de idiomas", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))
        questions.add(Question("What can you do?", "¿Qué puedes hacer?", "Comunicador multilingüe, solucionador de problemas", language=LANGUAGE.SPANISH, mode=QUESTIONMODE.REVERSE))


        questions.forEach{it.answer=it.answer.lowercase().trimEnd('?','.','!')}
        questions.forEach{it.noiseWords=it.noiseWords.lowercase().trimEnd('?','.','!')}
        if (DDL_SETTING.lowercase()=="create"){
            questionRepo.saveAll(questions)
            userService.register(User(username="Ryan",password="password123"))
        }


    }

}