name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
         working-directory: ./ReactLexiLucha/
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-react-app .

    - name: Run Docker container
      run: docker run -d -p 4000:3000 my-react-app
