name: Build and Run Docker Image

on:
  push:
    branches:
      - main
env:
  FE_NAME: react-app
jobs:
  build-and-run:
    runs-on: self-hosted
    env:
      DOCKER_CONTAINER_NAME: my-react-container
      DOCKER_IMAGE_NAME: my-react-app
    defaults:
      run:
         working-directory: ./ReactLexiLucha/
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker build .

    - name: Run Docker container
      run: docker run -d -p 4000:3000 $DOCKER_CONTAINER_NAME
