name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action

    - name: Build Docker image
      run: docker build -t my-react-app .

    - name: Run Docker container
      run: docker run -d -p 5000:3000 my-react-app
