name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Docker Compose
      #   uses: docker/compose-cli@v0.1.1
      #   with:
      #     compose-file: docker-compose.yml
      - id: string
        uses: Entepotenz/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}
      - name: Stop and remove existing containers
        run: echo "docker compose -p ${{ steps.string.outputs.lowercase }} down"

      - name: Build and run Docker Compose
        run: docker compose -p ${{ steps.string.outputs.lowercase }} up --build -d
